### ISSUE TITLE
Terrain translator improvements

### ISSUE THREAD

**Issue by ChiefOfGxBxL** [ChiefOfGxBxL/WC3MapTranslator#15]
1. Does the format for the JSON file need to be changed?
2. Add support for `war3map.w3e` --> `JSON`

**Comment by ttay24** [comment]
Took a stab at this: https://github.com/ttay24/WC3MapTranslator/tree/feature/terrain-translation

Working fine until we get to the second "row" of the tile data...then it affects the data from the first row. Not really sure why though
