### ISSUE TITLE
warToJson Strings

### ISSUE THREAD

**Issue by Promises** [ChiefOfGxBxL/WC3MapTranslator#17]
any plans for war2Json for the strings?

**Comment by ChiefOfGxBxL** [comment]
Yes, a warToJson method for the strings file will be written and released soon.

**Comment by ChiefOfGxBxL** [comment]
@Promises 

The newly-published [v1.1](https://www.npmjs.com/package/wc3maptranslator) implements the `warToJson` method for Strings. The source code here on GitHub also has an example under [examples/warToJson](https://github.com/ChiefOfGxBxL/WC3MapTranslator/blob/master/examples/warToJson/other/strings.js)

**Comment by Promises** [comment]
awesome, made my own in go, but awesome either way :P
