### ISSUE TITLE
Which node.js version is required?

### ISSUE THREAD

**Issue by ololoe** [ChiefOfGxBxL/WC3MapTranslator#21]

**Comment by ChiefOfGxBxL** [comment]
Hi @ololoe, I use version 8 (specifically v8.12.0).

Are you running into issues with a node version on your end?

**Comment by ololoe** [comment]
I'm using v5.12.0 which is the latest on win xp and it doesn't work.

**Comment by ChiefOfGxBxL** [comment]
It's possible that v5 is too old to support the newer features of Node that are in use in this application. I can dive deeper this weekend to confirm whether this is the case or not, but I'm guessing you'd need to use a newer version somehow.

**Comment by ololoe** [comment]
At least you should write versions of software project was tested with into project description.

**Comment by rufreakde** [comment]
@ololoe don't be mean if you try to run the project with an older node version the error will tell you the problem.

https://nodejs.org/api/buffer.html

Buffer works differently before version 6.0.0 and Node.js 8.0.0. there is your problem.

I think the Issue can be closed. With an update of the readme with a "requirements" section at the top.

**Comment by ChiefOfGxBxL** [comment]
Thanks @rufreakde for clarifying this version requirement. I've made a quick edit to the `README.md` file under the Install section to specify that version >= 8 is required.

**Comment by ololoe** [comment]
@rufreakde Why am I mean? It is normal to publish requirements.
