### ISSUE TITLE
npm start Error under /examples/ 

### ISSUE THREAD

**Issue by QGB** [ChiefOfGxBxL/WC3MapTranslator#37]
C:\test\node>cd C:\test\node\node_modules\wc3maptranslator\examples\warToJson

C:\test\node\node_modules\wc3maptranslator\examples\warToJson>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN warToJson@1.0.0 No repository field.

added 7 packages from 3 contributors and audited 7 packages in 3.505s
found 0 vulnerabilities

C:\test\node\node_modules\wc3maptranslator\examples\warToJson>npm start

> warToJson@1.0.0 start C:\test\node\node_modules\wc3maptranslator\examples\warToJson
> node index.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\test\node\node_modules\wc3maptranslator\examples\warToJson\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! warToJson@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the warToJson@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qgb\AppData\Roaming\npm-cache\_logs\2019-12-16T17_35_37_848Z-debug.log

C:\test\node\node_modules\wc3maptranslator\examples\warToJson>node -v
v12.13.1

C:\test\node\node_modules\wc3maptranslator\examples\warToJson>npm -v
6.13.4

C:\test\node\node_modules\wc3maptranslator\examples\warToJson>

**Comment by ChiefOfGxBxL** [comment]
Hi @QGB,

I apologize for this error - I am redoing the examples to reflect the recent change to TypeScript. Right now they are temporarily removed, but the `package.json`s and folders weren't removed, so that's why you're seeing this error.

I'll aim to get the updated examples posted tomorrow or Wednesday. They will certainly be available by Saturday at the latest.

**Comment by ChiefOfGxBxL** [comment]
Hi @QGB,

I've posted an update to the examples that uses TypeScript. Could you give it a test run? You'll need to `npm install` and then `npm start` under the `/examples/` directory.

If you encounter any issues with the updates, just create a new issue and I'll take a look. Thanks!
