### ISSUE TITLE
There is no permission to use the code.

### ISSUE THREAD

**Issue by poikilos** [ChiefOfGxBxL/WC3MapTranslator#44]
You can add a license easily using the GitHub website if you:
- Log in.
- Go to your [repo](https://github.com/actboy168/pjass-chs).
- Click "New File."
- For the name, type "license.txt" or something. That will cause the license template chooser to appear.
- Choose a license from the list.
- Choose "commit directly to the master branch"

Please make this MIT-licensed or something permissive if you don't care about it. That way others can use it. See https://github.com/poikilos/refounded . People can't use it if you don't provide a license, since the default legally is "[no permission](https://choosealicense.com/no-permission/)".

**Comment by ChiefOfGxBxL** [comment]
Thanks for pointing this out.

The README had a small badge indicating MIT, but it's easy to miss that. I added a specific LICENSE.md file to clarify this. The project is available under MIT.
