### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Bralukhis** [ChiefOfGxBxL/WC3MapTranslator#68]
I'm sorry if this is such a low level question but I am trying to edit the war3map.doo file for a map and I honestly have no idea how to even begin running this program but it seems to be the only one online with the potential capability to do so. Would it be possible for me to get pointed towards how to use the program? I am familiar with Java and C++ but I've never used TypeScript

**Comment by ChiefOfGxBxL** [comment]
Hi @Bralukhis,

This tool might be able to help you. It can take your `war3map.doo` file and convert it into a JSON representation, which may be easier to read and also programmatically manipulate.

Out of curiosity, what exactly are you looking to do with the `war3map.doo` file? Is there something that World Editor isn't making it easy to accomplish that you're hoping another tool will help with?

If you've never used TypeScript before, you may want to familiarize yourself with the [NodeJS ecosystem](https://nodejs.org/en/) first, including how to use [npm, the package manager](https://www.npmjs.com/).
