### ISSUE TITLE
Latest npm version is not built to JS

### ISSUE THREAD

**Issue by Slayer95** [ChiefOfGxBxL/WC3MapTranslator#69]

**Comment by ChiefOfGxBxL** [comment]
Hi @Slayer95, could you please try the latest version of `wc3maptranslator` (v4.0.4) by re-installing the latest? Does that resolve the issue for you?

**Comment by Slayer95** [comment]
Hello, @ChiefOfGxBxL . Thanks for taking care of the issue. The package is correctly installed now.
