### ISSUE TITLE
What is the difference between real and unreal?

### ISSUE THREAD

**Issue by yatyricky** [ChiefOfGxBxL/WC3MapTranslator#7]
What are they and how to choose the type?

**Comment by ChiefOfGxBxL** [comment]
Hi @yatyricky,

Real and unreal are nearly the same, except one is a signed number and the other isn't:
 * Real - signed real number
 * Unreal - unsigned real number

When deciding which type to use, it can be confusing and time-consuming. Below I provided an example:

**Finding the type of Holy Light's "amount healed"** (AHhb)  
Is amount healed an integer, real, or unreal?
1. Find the corresponding entry in `WorldEditStrings`, located in `War3.mpq > UI` (you'll need an MPQ editor for this, e.g. Ladik's MPQ Editor)
2. We see a suspecting WE string for "WESTRING_AEVAL_HHB1=Amount Healed/Damaged", which clearly corresponds with Holy Light's *amount healed* field, and also the _HHB1 name suggests that this is for the *AHhb* ability.
3. Find the row in `AbilityMetaData.slk` where the `displayName` matches "WESTRING_AEVAL_HHB1". This row contains which type to use. Screenshot posted below.

*Discovering the type (unreal) to use for Holy Light's "amount healed" data*
![image](https://user-images.githubusercontent.com/4079034/38420818-0e40a962-3973-11e8-8458-fc10024b359c.png)

---

I realize the process could be easier, but am on the fence if it should be WC3MapTranslator that implements this lookup logic, or if that would be left to a higher-level application (e.g. Ice Sickle).

At the very least, I will write good documentation this weekend and post it on this project's Wiki.

Hope my answer helps. If not feel free to ask for clarification. I'll close this issue in a few days if there are no further questions 😃

**Comment by yatyricky** [comment]
Hi @ChiefOfGxBxL , thank you for the response which explains my questions nice and clear. It can be closed now.
