### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Maj-ew** [ChiefOfGxBxL/WC3MapTranslator#73]
So installed it with npm install wc3maptranslator
Now there are some files in the folder where I installed it.
But the problem is what are the commands to use it? I am left on cmd opened in installed module directory
for example I have w3i extracted from map, how do I unpack it to json or just some readable text and then pack it back again?
Sry so far I only managed to understand python and Visual Studio compiling because it's very easy, but here it's like completely 0 info about anything

**Comment by ChiefOfGxBxL** [comment]
Hi @Maj-ew,

This is a [Node.js](https://nodejs.org/en) project, so you can use this package to write Node.js code to translate between JSON and war3map file formats. There's an [example usage in the README](https://github.com/ChiefOfGxBxL/WC3MapTranslator#usage) that might be helpful.

Also note that I've created a ticket for making this project act as a CLI tool as well: https://github.com/ChiefOfGxBxL/WC3MapTranslator/issues/72. This way users won't need to write Node.js code to get the benefit of this project. I'll get on top of that work soon, hopefully around the end of the year! You should be able to follow #72 for updates!

Best,
chiefofgxbxl

**Comment by Maj-ew** [comment]
yeah that would be nice I seem to not understand how to use this module, probably because there is only one example and only people who are well known to Node.js know how to use this

**Comment by ChiefOfGxBxL** [comment]
@Maj-ew Following up on the status of the CLI tool I mentioned earlier - I've got it nearly completed in #77, so once that's released soon you should be able to translate between JSON and War3Map files without having to use this tool programmatically. 😄
