### ISSUE TITLE
Extracting the scripts

### ISSUE THREAD

**Issue by VioletFlare** [ChiefOfGxBxL/WC3MapTranslator#75]
Hi, two questions: 

1. I haven't found any mention of extracting scripts with this lib. Is it possible or should I look somewhere else?
2. Is it possible to extract the whole w3x archive file? (trying to understand the structure of the archive... binwalk says it has thousands of zlib compressed blocks which upon extraction do not yield unit files, region files etc.)

Thanks.

**Comment by VioletFlare** [comment]
I found out that it was a MPQ archive by using `file`. I found a repo called `MPQExtractor` and used it to extract the w3x archive.

**Comment by ChiefOfGxBxL** [comment]
@VioletFlare Glad to hear you figured it out! Yea, any MPQ tool can help you get the files out of your map. I use [Ladik's MPQ Editor](https://www.hiveworkshop.com/threads/ladiks-mpq-editor.249562/).
